name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Node.js (for the web application)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install npm dependencies and build the application
      - name: Install npm dependencies
        run: |
          npm ci
          npm run build
        working-directory: iku

      # Start the web application in the background
      - name: Start web application
        run: |
          nohup npm start &
        working-directory: iku

      # Wait for the web application to start
      - name: Wait for the web application to start
        run: |
          sleep 10

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev
      - name: Test with pytest
        run: |
          pip install pytest
          pip install selenium
          pip install webdriver_manager
      - name: Run test suite
        run: |
          pipenv run pytest -v
